### ISSUE TITLE
Resize the category divs

### ISSUE THREAD

**Issue by vibeyInfotech** [vibeyInfotech/Project_03#1]
Add height and width and also add padding to the category divs

**Comment by yasirali786110** [comment]
Hi, I want to do that issue can you please assign it to me?

**Comment by suresh8919** [comment]
Hey @vibeyInfotech Can you Please assign me this

**Comment by premtw** [comment]
Hi @vibeyInfotech Can you please assign the issue. I'm eager to work on it
