### ISSUE TITLE
Convert the "Latest Article" Section into The Card

### ISSUE THREAD

**Issue by vibeyInfotech** [vibeyInfotech/Project_03#2]
Convert the "Latest Article" Section into The Card

**Comment by Prasanthisandaka2005** [comment]
Hello @vibeyInfotech,

I'm Prasanthi Sandaka, and I hope you're doing well.

I've been eager to contribute to the project, but I couldn't locate the website link associated with it. I was wondering if you could kindly provide me with the necessary information and access to the project. Once I have the details, I'm committed to making valuable contributions.

Please assign this task to me. I'm excited about the opportunity to contribute.
Thank you for considering my interest, and I look forward to your guidance and assignment.

**Comment by premtw** [comment]
Hi @vibeyInfotech Can you please assign the issue. I'm eager to work on it

**Comment by Tejoooo** [comment]
Heyy I m interested to work on this can you assign me to this issue
